/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'philc_000' at '06/02/17 22:24' with Gradle 2.13
 *
 * @author philc_000, @date 06/02/17 22:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
